### ISSUE TITLE
Guard against setting _node property if given a path in #getBoundCacheNode()

### ISSUE THREAD

**Issue by jhamlet** [graphistry/falcor#4]
@trxcllnt as discovered earlier today -- should guard against setting the _node property on the model if the function is given a path (happened when using #getVersion(path)).

**Comment by trxcllnt** [comment]
@jhamlet fixed in 83464cf4e6eaba6f0d69f83a3c4479e7bfc58c00 and @graphistry/falcor@2.0.6 in npm.
