### ISSUE TITLE
Breaking api change regarding paths on getValue

### ISSUE THREAD

**Issue by drFabio** [graphistry/falcor#5]
getValue is not parsing a path here https://github.com/graphistry/falcor/blob/master/packages/falcor/lib/get/getValue.js#L5

While on Netflix falcor it accepts an unparsed path https://github.com/Netflix/falcor/blob/master/lib/get/getValue.js#L5.
Was this an intentional api change?

**Comment by trxcllnt** [comment]
@drFabio yes, per the [readme](https://github.com/graphistry/falcor/blob/master/packages/falcor/README.md) in the falcor-client project, the path-syntax was removed from the core dist to cut down on compilation size and speed. If you're using Rx, the companion [`falcor-model-rxjs`](https://github.com/graphistry/falcor/blob/master/packages/falcor-model-rxjs/src/Model.js) project does automatically run arguments through the path syntax parser.

That said, we use the alternate [`falcor-query-syntax`](https://github.com/graphistry/falcor/tree/master/packages/falcor-query-syntax) in conjunction with the Mode's new `recycleJSON` option, which uses the query-syntax AST to optimize cache searches by comparing hash codes between the get request and the Model's deref'd JSON node.

**Comment by drFabio** [comment]
Ok. Just wanted to know if that was intentional.
Thanks for the response!
