### ISSUE TITLE
falcor-router wrong path resolution.

### ISSUE THREAD

**Issue by drFabio** [graphistry/falcor#7]
Handling a path with the form of:
``` javascript
"foo.WHATEVER"{
  call(pathSet, args) {
    return [
        {
          "path": [
            "bar",
            "baz"
          ],
          "value": 1
        },
        {
          "path": [
            "foo",
            "zap",
            0
          ],
          "value": 2
        }
    ]
  }
}

```
The resullting jsonGraph will be:
``` javascript
{
  foo: {
    "bar":{
      "baz":1 //WRONG
    },
    "zap":{
      0:2
    }
  }
}
```
While on falcor-router the same response has the correct structure

``` javascript
{
  "bar":{
    "baz":1 
  foo: {
    "zap":{
      0:2
    }
  }
}
```
The first path is concatenated with the root (thisPath) of the call path, the remaining paths goes unchanged

**Comment by trxcllnt** [comment]
@drFabio Sorry for the delay, I didn't have notifications on for the project :/. This should be fixed in the latest published version of the Router.

**Comment by drFabio** [comment]
No worries. Thanks for the response
